apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations: |
    argoproj.io/WorkflowTemplate:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = ""
        return hs
