apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: iperf3-network-test-6
  namespace: argocd
  labels:
    workflow: iperf3-test
spec:
  activeDeadlineSeconds: 3600 # 1 hour total workflow timeout

  entrypoint: network-test-suite
  arguments:
    parameters:
      - name: server-label
        value: role=blue
      - name: client-label
        value: role=red
      - name: test-duration
        value: "150"
      - name: cleanup-wait
        value: "10"
      - name: server-startup-wait
        value: "10"

  templates:
    - name: network-test-suite
      steps:
        # - - name: cleanup-previous
        #     template: cleanup-previous
        - - name: get-server-nodes
            template: get-server-nodes
        - - name: get-client-nodes
            template: get-client-nodes
        - - name: deploy-servers
            template: iperf3-server-step
            arguments:
              parameters:
                - name: server-nodes
                  value: "{{steps.get-server-nodes.outputs.result}}"
        - - name: wait-for-servers
            template: wait-for-servers
        - - name: test-10mbps
            template: iperf3-client-step
            arguments:
              parameters:
                - name: bandwidth
                  value: "10M"
                - name: test-name
                  value: "low-bandwidth"
                - name: client-nodes
                  value: "{{steps.get-client-nodes.outputs.result}}"
                - name: server-nodes
                  value: "{{steps.get-server-nodes.outputs.result}}"
                - name: test-duration
                  value: "{{workflow.parameters.test-duration}}"
        - - name: final-cleanup
            template: cleanup-all

    - name: cleanup-previous
      script:
        image: bitnami/kubectl
        command: [bash]
        source: |
          set -ex
          echo "Starting cleanup process..."
          kubectl delete pods -n argocd $(kubectl get pods -n argocd | grep ^iperf3- | awk '{print $1}') --force --grace-period=0
      activeDeadlineSeconds: 60

    - name: get-server-nodes
      script:
        image: bitnami/kubectl
        command: [bash]
        source: |
          kubectl get nodes -l {{workflow.parameters.server-label}} -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | jq -R . | jq -s .
      activeDeadlineSeconds: 30

    - name: get-client-nodes
      script:
        image: bitnami/kubectl
        command: [bash]
        source: |
          kubectl get nodes -l {{workflow.parameters.client-label}} -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | jq -R . | jq -s .
      activeDeadlineSeconds: 30

    - name: iperf3-server-step
      inputs:
        parameters:
          - name: server-nodes
      steps:
        - - name: deploy-server
            template: iperf3-server
            arguments:
              parameters:
                - name: node
                  value: "{{item}}"
            withParam: "{{inputs.parameters.server-nodes}}"

    - name: wait-for-servers
      script:
        image: bitnami/kubectl
        command: [bash]
        source: |
          echo "Waiting {{workflow.parameters.server-startup-wait}} seconds for servers to be ready..."
          sleep {{workflow.parameters.server-startup-wait}}
          kubectl wait --for=condition=ready pod -l app=iperf3-server -n argocd --timeout=60s
      activeDeadlineSeconds: 120

    - name: iperf3-server
      inputs:
        parameters:
          - name: node
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: Pod
          metadata:
            name: iperf3-server-{{inputs.parameters.node}}
            namespace: argocd
            labels:
              app: iperf3-server
              workflow: iperf3-test
          spec:
            nodeSelector:
              kubernetes.io/hostname: "{{inputs.parameters.node}}"
            containers:
            - name: server
              image: nicolaka/netshoot
              command: ["iperf3", "-s"]
              ports:
              - containerPort: 5201
            restartPolicy: Never

    - name: iperf3-client-step
      inputs:
        parameters:
          - name: bandwidth
          - name: test-name
          - name: client-nodes
          - name: server-nodes
          - name: test-duration
      script:
        image: bitnami/kubectl
        command: [bash]
        source: |
          set -ex
          CLIENTS=$(echo '{{inputs.parameters.client-nodes}}' | jq -r '.[]')
          SERVERS=$(echo '{{inputs.parameters.server-nodes}}' | jq -r '.[]')

          for CLIENT in $CLIENTS; do
            for SERVER in $SERVERS; do
              TEST_NAME="iperf3-client-{{inputs.parameters.test-name}}-${CLIENT}-to-${SERVER}"
              cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Pod
          metadata:
            name: $TEST_NAME
            namespace: argocd
            labels:
              test-type: iperf3-client
              workflow: iperf3-test
          spec:
            nodeSelector:
              kubernetes.io/hostname: "$CLIENT"
            containers:
            - name: client
              image: nicolaka/netshoot
              command:
                - /bin/bash
                - -c
                - |
                  trap 'echo "Trap caught, executing cleanup..."; exit 0' TERM INT

                  set -x
                  SERVER_POD="iperf3-server-${SERVER}"
                  SERVER_ADDR="\$SERVER_POD.argocd.svc.cluster.local"

                  echo "Waiting for server to be ready..."
                  for i in \$(seq 1 30); do
                    if nc -z -w 1 \$SERVER_ADDR 5201; then
                      echo "Server is ready"
                      break
                    fi
                    echo "Waiting for server... attempt \$i"
                    sleep 2
                  done

                  echo "Running iperf3 test..."
                  RESULT=\$(timeout {{inputs.parameters.test-duration}} iperf3 -c \$SERVER_ADDR -b {{inputs.parameters.bandwidth}} -t {{inputs.parameters.test-duration}} -J || true)

                  if [ -z "\$RESULT" ]; then
                    echo "No result from iperf3"
                    exit 1
                  fi

                  echo "Raw result: \$RESULT"
                  BANDWIDTH=\$(echo "\$RESULT" | jq -r '.end.sum_received.bits_per_second')

                  if [ -z "\$BANDWIDTH" ] || [ "\$BANDWIDTH" = "null" ]; then
                    echo "Invalid bandwidth value"
                    exit 1
                  fi

                  echo "Pushing metrics..."
                  METRICS="# TYPE iperf3_bandwidth_bits_per_second gauge
                  iperf3_bandwidth_bits_per_second{test_name=\\\"{{inputs.parameters.test-name}}\\\",client_node=\\\"${CLIENT}\\\",server_node=\\\"${SERVER}\\\"} \$BANDWIDTH"

                  echo "\$METRICS" | curl --max-time 10 -v --data-binary @- http://pushgateway.monitoring.svc.cluster.local:9091/metrics/job/iperf3_test

                  echo "Test completed successfully"
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "250m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
              livenessProbe:
                exec:
                  command:
                  - pgrep
                  - iperf3
                initialDelaySeconds: 5
                periodSeconds: 10
              readinessProbe:
                exec:
                  command:
                  - pgrep
                  - iperf3
                initialDelaySeconds: 5
                periodSeconds: 10
            terminationGracePeriodSeconds: 30
            restartPolicy: Never
          EOF
                done
              done

              echo "Waiting for tests to complete..."
              for i in $(seq 1 30); do
                PENDING=$(kubectl get pods -n argocd -l test-type=iperf3-client -o jsonpath='{.items[?(@.status.phase!="Succeeded")].metadata.name}')
                if [ -z "$PENDING" ]; then
                  echo "All tests completed"
                  break
                fi
                echo "Waiting for tests to complete... attempt $i"
                sleep 10
              done

    - name: cleanup-all
      script:
        image: bitnami/kubectl
        command: [bash]
        source: |
          set -ex
          echo "Deleting all test resources..."
          kubectl delete pods -n argocd -l workflow=iperf3-test --force --grace-period=0 --wait=false || true

          echo "Removing finalizers from any stuck pods..."
          kubectl get pods -n argocd -l workflow=iperf3-test -o name | while read pod; do
            kubectl patch $pod -n argocd -p '{"metadata":{"finalizers":null}}' --type=merge || true
            kubectl delete $pod -n argocd --force --grace-period=0 --wait=false || true
          done

          sleep {{workflow.parameters.cleanup-wait}}

          REMAINING=$(kubectl get pods -n argocd -l workflow=iperf3-test -o name | wc -l)
          echo "Remaining pods: $REMAINING"
          exit 0
      activeDeadlineSeconds: 60
