apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: iperf3-network-test
  namespace: argocd
spec:
  entrypoint: network-test-suite
  templates:
    - name: network-test-suite
      steps:
        - - name: create-server-service
            template: iperf3-service
        - - name: deploy-server
            template: iperf3-server
        - - name: test-10mbps
            template: iperf3-client
            arguments:
              parameters:
                - name: bandwidth
                  value: "10M"
                - name: test-name
                  value: "low-bandwidth"
        - - name: test-100mbps
            template: iperf3-client
            arguments:
              parameters:
                - name: bandwidth
                  value: "100M"
                - name: test-name
                  value: "medium-bandwidth"
        - - name: test-1gbps
            template: iperf3-client
            arguments:
              parameters:
                - name: bandwidth
                  value: "1G"
                - name: test-name
                  value: "high-bandwidth"
        - - name: cleanup
            template: cleanup

    - name: iperf3-service
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: Service
          metadata:
            name: iperf3-server
            namespace: argocd
          spec:
            selector:
              app: iperf3-server
            ports:
              - protocol: TCP
                port: 5201
                targetPort: 5201

    - name: iperf3-server
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: Pod
          metadata:
            name: iperf3-server
            namespace: argocd
            labels:
              app: iperf3-server
          spec:
            nodeSelector:
              kubernetes.io/hostname: microk8s-01  # Replace with your first node name
            containers:
            - name: server
              image: networkstatic/iperf3
              command: ["iperf3", "-s"]
              ports:
              - containerPort: 5201
            restartPolicy: Never

    - name: iperf3-client
      inputs:
        parameters:
          - name: bandwidth
          - name: test-name
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: Pod
          metadata:
            name: iperf3-client-{{inputs.parameters.test-name}}
            namespace: argocd
          spec:
            nodeSelector:
              kubernetes.io/hostname: microk8s-02  # Replace with your second node name
            containers:
            - name: client
              image: networkstatic/iperf3
              command:
                - /bin/sh
                - -c
                - |
                  RESULT=$(iperf3 -c iperf3-server.argocd.svc.cluster.local -b {{inputs.parameters.bandwidth}} -t 30 -J)
                  BANDWIDTH=$(echo $RESULT | jq -r '.end.sum_received.bits_per_second')
                  curl --data-binary @- http://prometheus-pushgateway.monitoring.svc.cluster.local:9091/metrics/job/iperf3_test/test_name/{{inputs.parameters.test-name}} <<EOF
                  # TYPE iperf3_bandwidth_bits_per_second gauge
                  iperf3_bandwidth_bits_per_second{test_name="{{inputs.parameters.test-name}}"} $BANDWIDTH
                  EOF
            restartPolicy: Never

    - name: cleanup
      resource:
        action: delete
        manifest: |
          apiVersion: v1
          kind: Service
          metadata:
            name: iperf3-server
            namespace: argocd
        flags: ["--ignore-not-found"]
